version: '3.7'

#  定义服务
services:
  # spring-boot服务
  app-server:
    build:
      context: . # 配置需要构建Dockerfile的路径 相对于docker-compose.yml
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # 将本机8080端口映射到容器8080端口
    restart: always
    depends_on:
      - db # 需要依赖的服务 率先构建
      - redis
    environment: # 设置环境变量
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/card?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: my-secret-pw
      SPRING_REDIS.HOST: redis
    networks: # 网络 连接mysql和redis
      - backend
  db:
    image: mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: card
      MYSQL_USER: root
      MYSQL_PASSWORD: my-secret-pw
      MYSQL_ROOT_PASSWORD: my-secret-pw
    volumes:
      - sql:/var/lib/mysql
    networks:
      - backend
  redis:
    image: redis
    command: [ "redis-server", "--protected-mode", "no" ]
    hostname:
      redis
    ports:
      - "6379:6379"
    networks:
      - backend
volumes:
  sql:
networks:
  backend: