sharingcard:
  uploadPath: c:/var/uploaded_files/
  starttime: 12
  endtime: 20
logging:
  level:
    root: info
    com.sharingcard: debug
wxinfo:
   appid: wxacab8bdcbe09a972
   secret: 36e2345d75caec2f2acd41069d3d0759
   openidurl: https://api.weixin.qq.com/sns/oauth2/access_token?appid={appid}&secret={secret}&code={code}&grant_type=authorization_code
   mch_appid: wx89d745228580fc4a
   mch_id: 1495127012
   mch_secret: 5e4dc0b28cd3d8ea89114af683d5c2a2
   company_pay_url: https://api.mch.weixin.qq.com/mmpaymkttransfers/promotion/transfers
   certPath: apiclient_cert.p12   
   transfercheck: true
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.116:3306/ppi?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: Aliyun67
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true
  redis:
      host: 192.168.2.20
      port: 6379
      password:
      # 连接超时时间（毫秒）
      timeout: 10000
      jedis:
        pool:
          # 连接池中的最大空闲连接
          max-idle: 8
          # 连接池中的最小空闲连接
          min-idle: 10
          # 连接池最大连接数（使用负值表示没有限制）
          max-active: 100
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1 

